name: Build and Create Tarball

on:
  push:
    branches:
      - branchAutomake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Automake
      run: |
        sudo apt-get update
        sudo apt-get install automake autoconf build-essential -y

    - name: Create tarball
      run: |
        ./configure
        make dist

