name: Build and Create Debian Package

on:
  push:
    branches:
      - branchAutoPackage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install devscripts dpkg-dev automake autoconf -y

    - name: Build Debian Package
      run: |
        ./configure
        make dist
        dpkg-buildpackage -us -uc

